[2024-05-24T04:09:33.736+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_teste_spark_documento_vencido_v01.elt_documento_pagar_spark scheduled__2020-11-29T01:00:00+00:00 [queued]>
[2024-05-24T04:09:33.759+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_teste_spark_documento_vencido_v01.elt_documento_pagar_spark scheduled__2020-11-29T01:00:00+00:00 [queued]>
[2024-05-24T04:09:33.760+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 11
[2024-05-24T04:09:33.937+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): elt_documento_pagar_spark> on 2020-11-29 01:00:00+00:00
[2024-05-24T04:09:33.949+0000] {standard_task_runner.py:57} INFO - Started process 249 to run task
[2024-05-24T04:09:33.954+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_teste_spark_documento_vencido_v01', 'elt_documento_pagar_spark', 'scheduled__2020-11-29T01:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/dag_teste/teste_***.py', '--cfg-path', '/tmp/tmpqykguu11']
[2024-05-24T04:09:33.958+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask elt_documento_pagar_spark
[2024-05-24T04:09:34.052+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_teste_spark_documento_vencido_v01.elt_documento_pagar_spark scheduled__2020-11-29T01:00:00+00:00 [running]> on host 575ebd466f13
[2024-05-24T04:09:34.236+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jozimar' AIRFLOW_CTX_DAG_ID='dag_teste_spark_documento_vencido_v01' AIRFLOW_CTX_TASK_ID='elt_documento_pagar_spark' AIRFLOW_CTX_EXECUTION_DATE='2020-11-29T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-11-29T01:00:00+00:00'
[2024-05-24T04:09:34.496+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_teste/teste_airflow.py", line 11, in processo_etl_spark
    sc = SparkContext(conf=conf)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-05-24T04:09:34.512+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_teste_spark_documento_vencido_v01, task_id=elt_documento_pagar_spark, execution_date=20201129T010000, start_date=20240524T040933, end_date=20240524T040934
[2024-05-24T04:09:34.531+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 72 for task elt_documento_pagar_spark ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 249)
[2024-05-24T04:09:34.546+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-24T04:09:34.569+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
